html
<!DOCTYPE html>
<html lang="hi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>YouTube Views</title>
    <style>
        /* Basic Reset */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            color: #333;
            line-height: 1.6;
        }

        /* Header */
        header {
            background: #ff0000;
            color: #fff;
            padding: 1rem 0;
            text-align: center;
        }

        header h1 {
            margin: 0;
        }

        /* Navigation */
        nav {
            background: #333;
            padding: 0.5rem;
            text-align: center;
        }

        nav a {
            color: #fff;
            margin: 0 10px;
            text-decoration: none;
        }

        nav a:hover {
            text-decoration: underline;
        }

        /* Main Content */
        .container {
            padding: 20px;
        }

        .video-section {
            margin-bottom: 20px;
        }

        .video-section h2 {
            margin-bottom: 10px;
        }

        .video-section iframe {
            width: 100%;
            height: 315px;
            border: none;
        }

        /* Form */
        .video-form {
            margin-bottom: 20px;
        }

        .video-form input[type="text"] {
            width: 70%;
            padding: 10px;
            margin-right: 10px;
            border: 1px solid #ccc;
        }

        .video-form button {
            padding: 10px 20px;
            background: #ff0000;
            color: #fff;
            border: none;
            cursor: pointer;
        }

        .video-form button:hover {
            background: #cc0000;
        }

        /* Footer */
        footer {
            background: #333;
            color: #fff;
            text-align: center;
            padding: 1rem 0;
            position: fixed;
            bottom: 0;
            width: 100%;
        }

        footer a {
            color: #ff0000;
            text-decoration: none;
        }

        footer a:hover {
            text-decoration: underline;
        }

        /* Hover Effects */
        button {
            transition: background 0.3s ease;
        }

        button:hover {
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
        }
    </style>
</head>
<body>

    <!-- Header -->
    <header>
        <h1>YouTube Views</h1>
    </header>

    <!-- Navigation -->
    <nav>
        <a href="#home">Home</a>
        <a href="#about">About</a>
        <a href="https://t.me/tenxfaster" target="_blank">Telegram</a>
    </nav>

    <!-- Main Content -->
    <div class="container" id="home">
        <!-- Video Input Form -->
        <form class="video-form" onsubmit="addVideo(event)">
            <input type="text" id="videoLink" placeholder="YouTube Video Link डालें..." required>
            <button type="submit">Add Video</button>
        </form>

        <!-- Video Sections -->
        <div id="videoContainer"></div>
    </div>

    <!-- About Section -->
    <div class="container" id="about">
        <h2>About</h2>
        <p>इस वेबसाइट का उद्देश्य यूज़र्स को YouTube वीडियो को एक साथ कई टैब में ओपन करने की सुविधा प्रदान करना है। आप यहाँ YouTube वीडियो लिंक डालकर उन्हें अपने ब्राउज़र में अलग-अलग टैब में ओपन कर सकते हैं।</p>
    </div>

    <!-- Footer -->
    <footer>
        <p>मेरे सोशल मीडिया पर जुड़ें: <a href="https://t.me/tenxfaster" target="_blank">Telegram</a></p>
    </footer>

    <script>
        // Function to add YouTube video
        function addVideo(event) {
            event.preventDefault();
            const videoLink = document.getElementById('videoLink').value;
            
            // Extract Video ID from the link
            const videoId = extractVideoId(videoLink);
            
            if (videoId) {
                // Create new video section
                const videoSection = document.createElement('div');
                videoSection.className = 'video-section';
                videoSection.innerHTML = `
                    <h2>Video ${document.querySelectorAll('.video-section').length + 1}</h2>
                    <iframe src="https://www.youtube.com/embed/${videoId}" allowfullscreen></iframe>
                `;
                
                // Append to video container
                document.getElementById('videoContainer').appendChild(videoSection);
                
                // Clear input
                document.getElementById('videoLink').value = '';
            } else {
                alert('Invalid YouTube Link!');
            }
        }

        // Function to extract YouTube Video ID
        function extractVideoId(url) {
            const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]*).*/;
            const match = url.match(regExp);
            return (match && match[2].length === 11) ? match[2] : null;
        }
    </script>
</body>
</html>
